### ISSUE TITLE
How to generate training data from DeMon

### ISSUE THREAD

**Issue by wangys8363** [AaltoML/GP-MVS#2]
I have downloaded the datasets of DeMon. However, I find that the sequences are all split  into several parts and each part only contains two images and correspongding cams. So how to merge these images into a complete sequence？

**Comment by fh1999** [comment]
Have you solved that question? I have the same problem.

**Comment by wangys8363** [comment]
> Have you solved that question? I have the same problem.

I've solved this partially by simply putting the training images into one folder and merging the images with the same cam parameters and you will find the image sequences easily. However, this method only works with some of the datasets.

**Comment by horizon0408** [comment]
You can use the script provided by DeepMVS, https://github.com/phuang17/DeepMVS/blob/master/python/download_training_datasets.py to get the image sequences data.
